variables:
  KW_PROJECT_NAME: openvkl

stages:
  - stage1
  - stage2
  - stage3

before_script:
  - git submodule sync
  - git submodule init
  - git submodule update

build-centos7:
  type: stage1
  image: openvkl/openvkl:centos7
  script:
    - gitlab/build.sh
  artifacts:
    paths:
    - build/
  tags:
    - docker

build-kw-scan:
  type: stage1
  image: openvkl/openvkl:centos7
  script:
    - gitlab/build-kw-scan.sh
  tags:
    - kw-scan-docker
  artifacts:
    paths:
        - $CI_PROJECT_DIR/kw_build_number
    expire_in: 1 day
  dependencies: []

source-protex-scan:
  type: stage1
  image: openvkl/openvkl:centos7
  script:
    - gitlab/source-scan-protex.sh
  tags:
    - docker
  dependencies: []
  allow_failure: true

test-kw-critical:
  type: stage2
  image: openvkl/openvkl:centos7
  script:
    - gitlab/test-kw-critical.sh
  dependencies:
    - build-kw-scan
  tags:
    - kw-scan-docker

test-functional-centos7:
  type: stage3
  image: openvkl/openvkl:centos7
  script:
    - ./build/vklTests
  dependencies:
    - build-centos7
  tags:
    - docker
